version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/wops-bi-slack-bot

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: ec2-user