version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/wops-bi-slack-bot

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: ubuntu